#!/usr/bin/env python3

import logging
from typing import Optional, Union

import panflute as pf


logger = logging.Logger("bibliography_table")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.FileHandler("bibliography_table.log"))


DEFAULT_HEADER_TEXT = "References"
DEFAULT_TARGET_DIV_ID = "reference_table"

class BibliographyTableDoc(pf.Doc):
    bibliography_rows: list[pf.TableRow]
    bibliography_table_target: str


def metadata_string(
    doc: pf.Doc,
    key: str,
    default: str,
) -> str:
    value = doc.get_metadata(key, default=default)

    if isinstance(value, str):
        return value

    return pf.stringify(value).strip()


def prepare(doc: BibliographyTableDoc) -> None:
    doc.bibliography_rows = []
    doc.bibliography_table_target = metadata_string(
        doc,
        "bibliography-table-target",
        DEFAULT_TARGET_DIV_ID,
    )
    logger.debug(doc)

def is_bibliography_div(elem: pf.Element) -> bool:
    """
    Checks if the given element is a bibliography div.

    :param elem: The element to check.
    :return: True if the element is a bibliography div, False otherwise.
    """
    return (
        isinstance(elem, pf.Div)
        and (
            elem.identifier == "refs"
            or "refs" in elem.classes
            or "references" in elem.classes
        )
    )


def is_target_bibliography_table_div(
    elem: pf.Element,
    doc: BibliographyTableDoc,
) -> bool:
    return (
        isinstance(elem, pf.Div)
        and elem.identifier == doc.bibliography_table_target
    )


def is_empty_block(block: pf.Block) -> bool:
    """
    Checks if the given block has no visible text content.

    :param block: The block to check.
    :return: True if the block is empty, False otherwise.
    """
    return pf.stringify(block).strip() == ""


def cell_from_text(text: str) -> pf.TableCell:
    """
    Creates a table cell from plain text.

    :param text: The text to place in the cell.
    :return: A table cell containing the text.
    """

    logger.debug("What is the text??? %s", text)

    return pf.TableCell(
        pf.Plain(pf.Str(text))
    )


def cell_from_blocks(blocks: list[pf.Block]) -> pf.TableCell:
    """
    Creates a table cell from one or more Pandoc blocks.

    :param blocks: The blocks to place in the cell.
    :return: A table cell containing the blocks.
    """
    return pf.TableCell(*blocks)


def bibliography_entry_to_row(entry: pf.Block) -> pf.TableRow:
    """
    Converts one citeproc-generated bibliography block into a table row.

    :param entry: The citeproc-generated bibliography block.
    :return: A single-cell table row.
    """
    logger.debug(entry)

    return pf.TableRow(
        cell_from_blocks([entry])
    )


def bibliography_blocks_to_rows(blocks: list[pf.Block]) -> list[pf.TableRow]:
    """
    Converts citeproc-generated bibliography blocks into table rows.

    :param blocks: The bibliography blocks from the refs div.
    :return: A list of table rows.
    """
    rows: list[pf.TableRow] = []

    for block in blocks:
        if is_empty_block(block):
            continue

        rows.append(bibliography_entry_to_row(block))

    return rows


def bibliography_to_table(bibliography: pf.Div) -> Union[pf.Table, list[pf.Block]]:
    """
    Converts a citeproc-generated bibliography div into a single-column table.

    If a table already exists inside the refs div, bibliography rows are added
    to that table so the existing caption, identifier, and numbering metadata
    are preserved.

    :param bibliography: The bibliography div generated by citeproc.
    :return: A table, or the refs div content with the table filled.
    """
    existing_table: pf.Table | None = None
    bibliography_blocks: list[pf.Block] = []
    other_blocks: list[pf.Block] = []

    for block in bibliography.content:
        if is_bibliography_table(block) and existing_table is None:
            existing_table = block
        elif is_bibliography_table(block):
            other_blocks.append(block)
        else:
            bibliography_blocks.append(block)

    rows = bibliography_blocks_to_rows(bibliography_blocks)

    logger.debug("Converting citeproc bibliography to table")
    logger.debug("Found %d bibliography rows", len(rows))
    logger.debug("Rows: %s", rows)
    logger.debug("Existing table found: %s", existing_table is not None)

    if existing_table is not None:
        filled_table = add_rows_to_existing_table(existing_table, rows)

        return [
            filled_table,
            *other_blocks,
        ]

    header = pf.TableHead(
        pf.TableRow(
            cell_from_text(DEFAULT_HEADER_TEXT)
        )
    )

    body = pf.TableBody(*rows)

    return pf.Table(
        body,
        caption=pf.Caption(),
        head=header,
        colspec=[("AlignDefault", 1.0)],
    )


def is_bibliography_table(block: pf.Block) -> bool:
    return isinstance(block, pf.Table)


def get_existing_table_rows(table: pf.Table) -> list[pf.TableRow]:
    rows: list[pf.TableRow] = []

    for body in table.content:
        if isinstance(body, pf.TableBody):
            rows.extend(list(body.content))

    return rows


def is_placeholder_row(row: pf.TableRow) -> bool:
    return pf.stringify(row).strip() == "placeholder"


def remove_placeholder_rows(rows: list[pf.TableRow]) -> list[pf.TableRow]:
    return [
        row
        for row in rows
        if not is_placeholder_row(row)
    ]


def add_rows_to_existing_table(
    table: pf.Table,
    rows_to_add: list[pf.TableRow],
) -> pf.Table:
    existing_rows = remove_placeholder_rows(get_existing_table_rows(table))

    rows = [
        *existing_rows,
        *rows_to_add,
    ]

    return pf.Table(
        pf.TableBody(*rows),
        caption=table.caption,
        head=table.head,
        foot=table.foot,
        colspec=table.colspec,
    )


def populate_table_div(
    table_div: pf.Div,
    rows: list[pf.TableRow],
) -> list[pf.Block]:
    populated_blocks: list[pf.Block] = []
    table_found = False

    for block in table_div.content:
        if is_bibliography_table(block) and not table_found:
            populated_blocks.append(add_rows_to_existing_table(block, rows))
            table_found = True
        else:
            populated_blocks.append(block)

    if table_found:
        return populated_blocks

    header = pf.TableHead(
        pf.TableRow(
            cell_from_text(DEFAULT_HEADER_TEXT)
        )
    )

    body = pf.TableBody(*rows)

    return [
        pf.Table(
            body,
            caption=pf.Caption(),
            head=header,
            colspec=[("AlignDefault", 1.0)],
        )
    ]


def action(
    elem: pf.Element,
    doc: BibliographyTableDoc,
) -> Optional[Union[pf.Element, list[pf.Element]]]:
    if is_bibliography_div(elem):
        logger.debug("Found bibliography div")

        doc.bibliography_rows = bibliography_blocks_to_rows(list(elem.content))

        return []

    if is_target_bibliography_table_div(elem, doc):
        logger.debug("Found bibliography table target div: %s", elem.identifier)
        logger.debug("Adding %d bibliography rows", len(doc.bibliography_rows))

        return populate_table_div(elem, doc.bibliography_rows)

    return None


def main(doc: Optional[pf.Doc] = None) -> pf.Doc:
    logger.info("Starting bibliography-table-filter")

    result = pf.run_filter(action, prepare=prepare, doc=doc)

    logger.info("Finished bibliography-table-filter")

    return result


if __name__ == "__main__":
    main()